version: "2.0"
services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_HOST=postgres
    depends_on:
      - redis
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/app
    ports:
      - "80:80"
    depends_on:
      - api
      - client
