version: "2.0"
services:
  worker:
    image: kodega2016/fib-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  api:
    image: kodega2016/fib-api
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DATABASE=$PG_DATABASE
      - PG_PORT=$PG_PORT
      - PG_HOST=$PG_HOST
    depends_on:
      - redis
      - postgres
  client:
    image: kodega2016/fib-client
    hostname: client
    mem_limit: 128m
    depends_on:
      - api
  nginx:
    image: kodega2016/fib-nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
    depends_on:
      - api
      - client
