version: "3"
services:
  worker:
    image: rallycoding/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  api:
    image: rallycoding/multi-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DATABASE=$PG_DATABASE
      - PG_PORT=$PG_PORT
      - PG_HOST=$PG_HOST
  client:
    image: rallycoding/multi-client
    hostname: client
    mem_limit: 128m
    depends_on:
      - api
  nginx:
    image: rallycoding/multi-nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
    depends_on:
      - api
      - client
