name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build client dev image
        run: docker image build . -t kodega2016/react-app-dev -f ./client/Dockerfile.dev
      - name: run client tests
        run: docker container run -e CI=true --rm kodega2016/react-app-dev npm run test -- --coverage
